# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_ampa.ui'
#
# Created: Sun Jul 21 18:58:43 2019
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(729, 282)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.label_loaded = QtGui.QLabel(self.centralwidget)
        self.label_loaded.setText(_fromUtf8(""))
        self.label_loaded.setObjectName(_fromUtf8("label_loaded"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_loaded)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_2.addWidget(self.line)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_2.addWidget(self.label_6)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 0, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 1, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.windowAnalysis = QtGui.QDoubleSpinBox(self.centralwidget)
        self.windowAnalysis.setDecimals(1)
        self.windowAnalysis.setMaximum(3600.0)
        self.windowAnalysis.setSingleStep(5.0)
        self.windowAnalysis.setProperty("value", 200.0)
        self.windowAnalysis.setObjectName(_fromUtf8("windowAnalysis"))
        self.gridLayout.addWidget(self.windowAnalysis, 0, 1, 1, 1)
        self.percOverlap = QtGui.QDoubleSpinBox(self.centralwidget)
        self.percOverlap.setDecimals(1)
        self.percOverlap.setMaximum(100.0)
        self.percOverlap.setSingleStep(10.0)
        self.percOverlap.setProperty("value", 50.0)
        self.percOverlap.setObjectName(_fromUtf8("percOverlap"))
        self.gridLayout.addWidget(self.percOverlap, 1, 1, 1, 1)
        self.uValue = QtGui.QSpinBox(self.centralwidget)
        self.uValue.setMinimum(5)
        self.uValue.setMaximum(20)
        self.uValue.setProperty("value", 12)
        self.uValue.setObjectName(_fromUtf8("uValue"))
        self.gridLayout.addWidget(self.uValue, 1, 3, 1, 1)
        self.spinBox = QtGui.QSpinBox(self.centralwidget)
        self.spinBox.setMinimum(30)
        self.spinBox.setMaximum(100)
        self.spinBox.setProperty("value", 90)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.gridLayout.addWidget(self.spinBox, 0, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_2.addWidget(self.line_3)
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_2.addWidget(self.label_9)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.initialfreq = QtGui.QDoubleSpinBox(self.centralwidget)
        self.initialfreq.setDecimals(1)
        self.initialfreq.setMinimum(1.0)
        self.initialfreq.setMaximum(30.0)
        self.initialfreq.setSingleStep(1.0)
        self.initialfreq.setProperty("value", 2.0)
        self.initialfreq.setObjectName(_fromUtf8("initialfreq"))
        self.gridLayout_3.addWidget(self.initialfreq, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 0, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 1, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 0, 0, 1, 1)
        self.endfreq = QtGui.QDoubleSpinBox(self.centralwidget)
        self.endfreq.setDecimals(1)
        self.endfreq.setMaximum(30.0)
        self.endfreq.setSingleStep(1.0)
        self.endfreq.setProperty("value", 12.0)
        self.endfreq.setObjectName(_fromUtf8("endfreq"))
        self.gridLayout_3.addWidget(self.endfreq, 1, 1, 1, 1)
        self.lcoefficient = QtGui.QSpinBox(self.centralwidget)
        self.lcoefficient.setMinimum(1)
        self.lcoefficient.setMaximum(10)
        self.lcoefficient.setProperty("value", 5)
        self.lcoefficient.setObjectName(_fromUtf8("lcoefficient"))
        self.gridLayout_3.addWidget(self.lcoefficient, 1, 3, 1, 1)
        self.bandWidth = QtGui.QSpinBox(self.centralwidget)
        self.bandWidth.setMinimum(30)
        self.bandWidth.setMaximum(30)
        self.bandWidth.setProperty("value", 30)
        self.bandWidth.setObjectName(_fromUtf8("bandWidth"))
        self.gridLayout_3.addWidget(self.bandWidth, 0, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.buttonCancel = QtGui.QPushButton(self.centralwidget)
        self.buttonCancel.setObjectName(_fromUtf8("buttonCancel"))
        self.horizontalLayout.addWidget(self.buttonCancel)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        self.buttonComputePlot = QtGui.QPushButton(self.centralwidget)
        self.buttonComputePlot.setObjectName(_fromUtf8("buttonComputePlot"))
        self.horizontalLayout.addWidget(self.buttonComputePlot)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.tableWidget = QtGui.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(5)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        self.horizontalLayout_2.addWidget(self.tableWidget)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Multiprocessing Band Adaptation", None))
        self.label.setText(_translate("Multiprocessing Band Adaptation", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">Loaded Trace</span></p></body></html>", None))
        self.label_6.setText(_translate("Multiprocessing Band Adaptation", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">Modify Detector Parameters </span></p></body></html>", None))
        self.label_7.setText(_translate("Multiprocessing Band Adaptation", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Noise level Threshold (Perc)</span></p></body></html>", None))
        self.label_8.setText(_translate("Multiprocessing Band Adaptation", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Shift value (U)</span></p></body></html>", None))
        self.label_2.setText(_translate("Multiprocessing Band Adaptation", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Overlap (%)</span></p></body></html>", None))
        self.label_5.setText(_translate("Multiprocessing Band Adaptation", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Window of analysis (s)</span></p></body></html>", None))
        self.label_9.setText(_translate("Multiprocessing Band Adaptation", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">Modify Filter Parameters </span></p></body></html>", None))
        self.label_10.setText(_translate("Multiprocessing Band Adaptation", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Bandwidth (Hz)</span></p></body></html>", None))
        self.label_11.setText(_translate("Multiprocessing Band Adaptation", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Enhancement Coefficient</span></p></body></html>", None))
        self.label_3.setText(_translate("Multiprocessing Band Adaptation", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">End Frequency (Hz)</span></p></body></html>", None))
        self.label_12.setText(_translate("Multiprocessing Band Adaptation", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Initial Frequency (Hz)</span></p></body></html>", None))
        self.buttonCancel.setText(_translate("Multiprocessing Band Adaptation", "Cancel", None))
        self.pushButton.setText(_translate("Multiprocessing Band Adaptation", "Add Filter", None))
        self.buttonComputePlot.setText(_translate("Multiprocessing Band Adaptation", "Compute/Plot", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Multiprocessing Band Adaptation", "Filter 1", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Multiprocessing Band Adaptation", "Filter 2", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Multiprocessing Band Adaptation", "Filter 3", None))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Multiprocessing Band Adaptation", "Filter 4", None))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Multiprocessing Band Adaptation", "Filter 5", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Multiprocessing Band Adaptation", "Length (s)", None))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Multiprocessing Band Adaptation", "30.0", None))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("Multiprocessing Band Adaptation", "20.0", None))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("Multiprocessing Band Adaptation", "10.0", None))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("Multiprocessing Band Adaptation", "5.0", None))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("Multiprocessing Band Adaptation", "2.5", None))
        self.tableWidget.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

